package:
  format-version: "1.0.0"
  name: "gfx"
  version: "3.11.0"
  type: "api"
  status: "production"

  dependencies:
    - name: "core"
      type: "package"
      version: "3.11.1"
    - name: "touch"
      type: "package"
      version: "3.12.1"
