package:
  format-version: "1.0.0"
  name: "gfx"
  version: "v3.14.1"
  type: "api"
  status: "production"

  dependencies:
    - name: "core"
      type: "package"
      version: "v3.13.3"
    - name: "touch"
      type: "package"
      version: "v3.14.0"
